//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Seminar1.rc
//
#define IDD_SEMINAR1_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_APLIKACIJA           130
#define IDD_DIALOG_HOTEL                132
#define IDD_DIALOG_DODAJ_HOTEL          134
#define IDD_DIALOG_DODAJ_SOBU           136
#define IDD_DIALOG_POPIS_SOBA           138
#define IDD_DIALOG_ZAPOSLENIK           140
#define IDD_DIALOG_GOST                 142
#define IDD_DIALOG_DODAJ_ZAPOSLENIK     144
#define IDD_DIALOG_DODAJ_GOSTA          146
#define IDD_DIALOG_SLOBODNE_SOBE        148
#define IDD_DIALOG_NOVA_REZERVACIJA     150
#define IDD_DIALOG_LISTA_REZEVACIJA     152
#define IDD_DIALOG_STARE_REZERVACIJE    153
#define IDS_STRING_SOBA1                500
#define IDS_STRING_SOBA2                501
#define IDS_STRING_SOBA3                502
#define IDS_STRING_PAZNA_POLJA          503
#define IDS_STRING_GOST1                504
#define IDS_STRING_GOST2                505
#define IDS_STRING_HOTEL1               506
#define IDS_STRING_HOTEL2               507
#define IDS_STRING_ZAPOSLENIK1          508
#define IDS_STRING_ZAPOSLENIK2          509
#define IDS_STRING_PRINT1               510
#define IDS_STRING_PRINT2               511
#define IDS_STRING_PRINT3               512
#define IDS_STRING_PRINT4               513
#define IDS_STRING_PRINT5               514
#define IDS_STRING_PRINT6               515
#define IDS_STRING_PRINT7               516
#define IDS_STRING_PRINT8               517
#define IDS_STRING_PRINT9               518
#define IDS_STRING_KORISNIK_NEPOSTOJI   519
#define IDS_STRING_REZERVACIJA2         520
#define IDS_STRING_REZERVACIJA3         521
#define IDS_STRING_REZERVACIJA4         522
#define IDS_STRING_REZERVACIJA5         523
#define IDS_STRING_VALTUA               524
#define IDS_STRING_DATUM                700
#define IDS_STRING_NOCI                 701
#define IDS_STRING_BROJ_GOSTIJU         702
#define IDS_STRING_CHECK_IN             703
#define IDS_STRING_CHECK_OUT            704
#define IDS_STRING_GOST                 705
#define IDS_STRING_ZAPOSLENIK           706
#define IDS_STRING_UKUPNO               707
#define IDS_STRING_IME                  708
#define IDS_STRING_PREZIME              709
#define IDS_STRING_OIB                  710
#define IDS_STRING_ADRESA               711
#define IDS_STRING_GRAD                 712
#define IDS_STRING_DRZAVA               713
#define IDS_STRING_KONTAKT              714
#define IDS_STRING_ID                   715
#define IDS_STRING_NAZIV                716
#define IDS_STRING_OPIS                 717
#define IDS_STRING_DUHAN                718
#define IDS_STRING_LJUBIMAC             719
#define IDS_STRING_DA                   720
#define IDS_STRING_NE                   721
#define IDS_STRING_CIJENA               722
#define IDS_STRING_OSOBE                723
#define IDS_STRING_VRSTA_SOBE           724
#define IDS_STRING_OPIS_SOBE            725
#define IDS_STRING_MAX_OSOBA            726
#define IDS_STRING_OZNAKA               727
#define IDS_STRING_VRSTA                728
#define IDC_Korisnik                    1000
#define IDC_Lozinka                     1001
#define IDC_LOGIRAN                     1002
#define IDC_BUTTON_ODJAVA               1003
#define IDC_STATIC_KORISNIK             1004
#define IDC_BUTTON_HOTEL                1005
#define IDC_LIST_HOTELI                 1006
#define IDC_BUTTON_REZERVACIJE          1006
#define IDC_BUTTON_OHotel               1007
#define IDC_BUTTON_DODAJ_HOTEL	        1008
#define IDC_STATIC_Hotel_Naziv          1009
#define IDC_STATIC_Hotel_Adresa         1011
#define IDC_STATIC_Hotel_Grad           1012
#define IDC_STATIC_Hotel_Kontakt        1013
#define IDC_EDIT_Hotel_Naziv            1014
#define IDC_EDIT_Hotel_Adresa           1015
#define IDC_EDIT_Hotel_Grad             1016
#define IDC_EDIT_Hotel_Kontakt          1017
#define IDC_BUTTON_Hotel_DODAJ          1018
#define IDC_STATIC_Hotel_Stanje         1019
#define IDC_BUTTON_HOTEL_IZBRISI        1020
#define IDC_EDIT_Hotel_Trazi            1021
#define IDC_BUTTON_Hotel_Trazi          1022
#define IDC_BUTTON_DODAJ_SOBU           1024
#define IDC_CHECK_DUHAN                 1025
#define IDC_CHECK_LJUBIMCI              1026
#define IDC_COMBO_SOBA_VRSTA            1028
#define IDC_STATIC_HotelID              1029
#define IDC_STATIC_NazivHotela          1030
#define IDC_STATIC_SOBA_STATUS          1032
#define IDC_BUTTON_POPIS_SOBA           1033
#define IDC_STATIC_POPIS_HOTEL_ID       1034
#define IDC_STATIC_POPIS_NAZIV_HOTELA   1035
#define IDC_STATIC_POPIS_HID            1036
#define IDC_STATIC_POPIS_HNAZIV         1037
#define IDC_LIST_POPIS_SOBA             1038
#define IDC_BUTTON_POPIS_IZBRISI_SOBU   1039
#define IDC_BUTTON_ZAPOSLENIK           1041
#define IDC_BUTTON_GOST                 1043
#define IDC_LIST_POPIS_ZAPOSLENIKA      1044
#define IDC_BUTTON_ZAPOSLENIK_IZBRISI   1045
#define IDC_BUTTON_ZAPOSLENIK_DODAJ     1046
#define IDC_STATIC_Z1                   1047
#define IDC_STATIC_Z2                   1048
#define IDC_STATIC_Z3                   1049
#define IDC_STATIC_Z4                   1050
#define IDC_STATIC_Z5                   1051
#define IDC_STATIC_Z6                   1052
#define IDC_STATIC_Z7                   1053
#define IDC_STATIC_Z8                   1054
#define IDC_EDIT_Z_KOznaka              1055
#define IDC_EDIT_Z_Ime                  1056
#define IDC_EDIT_Z_Prezime              1057
#define IDC_EDIT_Z_Adresa               1058
#define IDC_EDIT_Z_Grad                 1059
#define IDC_EDIT_Z_Drzava               1060
#define IDC_EDIT_Z_Kontakt              1061
#define IDC_EDIT_Z_Lozinka              1062
#define IDC_STATIC_Z_STATUS             1063
#define IDC_LIST_GOSTI                  1064
#define IDC_EDIT_GOST_IME               1065
#define IDC_EDIT_GOST_PREZIME           1066
#define IDC_BUTTON1                     1066
#define IDC_BUTTON_DODAJ_GOSTA          1066
#define IDC_BUTTON_SLOBODNE_SOBE        1066
#define IDC_BUTTON_SLOBODNE_SOBE_PRIKAZ 1066
#define IDC_BUTTON_R_TRAZI              1066
#define IDC_BUTTON_R_PRINT              1066
#define IDC_EDIT_GOST_OIB               1067
#define IDC_COMBO_SLOBODNE_NAZIVHOTELA  1067
#define IDC_EDIT_GOST_ADRESA            1068
#define IDC_LIST_SLOBODNE_SOBE_POPIS    1068
#define IDC_EDIT_GOST_GRAD              1069
#define IDC_DATETIMEPICKER_SOBE         1069
#define IDC_EDIT_GOST_DRZAVA            1070
#define IDC_DATETIMEPICKER_COUT         1071
#define IDC_EDIT_GOST_KONTAKT           1072
#define IDC_BUTTON_NOVA_REZERVACIJA     1072
#define IDC_EDIT_R_IME                  1073
#define IDC_EDIT_R_PREZIME              1074
#define IDC_EDIT_R_ADRESA               1075
#define IDC_EDIT_R_GRAD                 1076
#define IDC_EDIT_R_DRZAVA               1077
#define IDC_EDIT_R_KONTAKT              1078
#define IDC_EDIT_R_OIB                  1079
#define IDC_EDIT_R_OIB_P                1080
#define IDC_STATIC_R_IMEGOSTA           1081
#define IDC_STATIC_R_DATUM              1082
#define IDC_EDIT_R_BROJGOSTIJU          1084
#define IDC_STATIC_R_UKUPNACIJENA       1087
#define IDC_STATIC_R_DATUMDOLASKA       1088
#define IDC_STATIC_R_DATUMODLASKA       1089
#define IDC_LIST_R_ODABRANESOBE         1090
#define IDC_EDIT_R_IDSOBE               1091
#define IDC_BUTTON_R_DODAJ              1092
#define IDC_BUTTON_R_IZBRISI            1093
#define IDC_STATIC_R_BROJNOCENJA        1094
#define IDC_LIST_REZERVACIJE            1096
#define IDC_LIST_REZERVACIJA_SOBE       1097
#define IDC_BUTTON_STARE_REZERVACIJE    1098
#define IDC_LIST_D_REZERVACIJE          1099
#define IDC_LIST_STARE_REZERVACIJE      1100

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1095
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
